name: ${COMPOSE_PROJECT_NAME:-patientbilling-prod}

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - prod_db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      ENV: prod
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -q 8000"]
      timeout: 5s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    restart: unless-stopped
    command: /bin/sh -c "/zango/scripts/sync_providers.sh && cd ${PROJECT_NAME} && celery -A ${PROJECT_NAME} worker -l info --concurrency=2"
    env_file:
      - .env.prod
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      app:
        condition: service_healthy

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_UID=${HOST_UID:-1000}
        - HOST_GID=${HOST_GID:-1000}
    restart: unless-stopped
    command: /bin/sh -c "/zango/scripts/sync_providers.sh && cd ${PROJECT_NAME} && single-beat celery -A ${PROJECT_NAME} beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - .env.prod
    environment:
      SINGLE_BEAT_REDIS_SERVER: redis://${REDIS_HOST}:${REDIS_PORT}/1
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  prod_db:
  caddy_data:
